# Generated by Django 4.2.1 on 2023-05-29 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_band_active_band_biography_band_genre_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='goodies',
            name='description',
            field=models.CharField(default='', max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='goodies',
            name='sold',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='goodies',
            name='type',
            field=models.CharField(choices=[('REC', 'Records'), ('CLTH', 'Clothing'), ('PSTR', 'Posters'), ('MSLS', 'Miscellaneous')], default='REC', max_length=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='goodies',
            name='year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
